### ISSUE TITLE
[Bug] null exception if target drawer inherented from an abstruct class

### ISSUE THREAD

**Issue by locus84** [TylerTemp/SaintsField#192]
**Describe the bug**
I'm using soap package for my game development which has own property drawer for it's types.

I see some null exceptions when clicked the gameobject and nowthing is drawn for the component.

```csharp
[SerializeField, GetScriptableObject("Assets/_Game/ScriptableObjects/DefaultUIDepth")]
private ScriptableListCanvas m_CanvasList;

[SerializeField, GetScriptableObject("Assets/_Game/ScriptableObjects/DefaultUIInteractable")]
private IntVariable m_BlockRequestCount;
```

**Unity Version**
6000.0.41f1

**SaintsField Version**
4.0.4

**Drawer Env**

- [x] UI Toolkit
- [ ] IMGUI
- [ ] I'm not sure / It's not related.

**Additional context**

```
NullReferenceException: Object reference not set to an instance of an object
SaintsField.Editor.Core.SaintsPropertyDrawer.CreatePropertyGUI (UnityEditor.SerializedProperty property) (at ./Library/PackageCache/today.comes.saintsfield@7aa21fa0a325/Editor/Core/SaintsPropertyDrawerUIToolkit.cs:306)
SaintsField.Editor.Playa.Renderer.SerializedFieldRenderer.CreateSerializedUIToolkit () (at ./Library/PackageCache/today.comes.saintsfield@7aa21fa0a325/Editor/Playa/Renderer/SerializedFieldRendererUIToolkit.cs:114)
SaintsField.Editor.Playa.Renderer.BaseRenderer.SerializedFieldBaseRenderer.CreateTargetUIToolkit (UnityEngine.UIElements.VisualElement container) (at ./Library/PackageCache/today.comes.saintsfield@7aa21fa0a325/Editor/Playa/Renderer/BaseRenderer/SerializedFieldBaseRendererUIToolkit.cs:41)
SaintsField.Editor.Playa.Renderer.BaseRenderer.AbsRenderer.CreateVisualElement () (at ./Library/PackageCache/today.comes.saintsfield@7aa21fa0a325/Editor/Playa/Renderer/BaseRenderer/AbsRendererUIToolkit.cs:48)
SaintsField.Editor.SaintsEditor.CreateInspectorGUI () (at ./Library/PackageCache/today.comes.saintsfield@7aa21fa0a325/Editor/SaintsEditorUIToolkit.cs:59)
UnityEditor.UIElements.InspectorElement.CreateInspectorElementUsingUIToolkit (UnityEditor.Editor targetEditor) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement.CreateInspectorElementFromSerializedObject (UnityEditor.SerializedObject bindObject) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement.HandleEventBubbleUp (UnityEngine.UIElements.EventBase evt) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventBubbleUpInternal (UnityEngine.UIElements.EventBase evt) (at <7878115525854df7993c2f050b5b1154>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEvent_BubbleUpHandleEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement element, System.Boolean disabled) (at <7878115525854df7993c2f050b5b1154>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEventAtTargetAndDefaultPhase (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target) (at <7878115525854df7993c2f050b5b1154>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.SendBindingEvent[TEventType] (TEventType evt, UnityEngine.UIElements.VisualElement target) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.BindTree (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedProperty parentProperty) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.ContinueBinding (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedProperty parentProperty) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.Bind (UnityEngine.UIElements.VisualElement element) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.DefaultSerializedObjectBindingImplementation.Bind (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedObject obj) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.BindingExtensions.Bind (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedObject obj) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement..ctor (UnityEditor.SerializedObject obj, UnityEditor.Editor editor, UnityEditor.UIElements.InspectorElement+DefaultInspectorFramework defaultInspectorFramework) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement..ctor (UnityEditor.Editor editor, UnityEditor.UIElements.InspectorElement+DefaultInspectorFramework defaultInspectorFramework) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement..ctor (UnityEditor.Editor editor) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.EditorElement.BuildInspectorElement () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.EditorElement.CreateInspectorElement () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.EditorElementUpdater.CreateInspectorElementsForMilliseconds (System.Int64 targetMilliseconds) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.PropertyEditor.Update () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.HostView.SendUpdate () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <95707308f6f3498991e9df8902fe97ba>:0)
```

**Comment by TylerTemp** [comment]
Fixed in [4.1.0](https://github.com/TylerTemp/SaintsField/releases/tag/4.1.0)

**Comment by locus84** [comment]
I've updated to version 4.1.0 but the issue still persists.
Any context that I can provide more?

**Comment by TylerTemp** [comment]
Hummm can you again paste the trackback log? Might be a different place

**Comment by locus84** [comment]
```
NullReferenceException: Object reference not set to an instance of an object
SaintsField.Editor.Core.SaintsPropertyDrawer.CreatePropertyGUI (UnityEditor.SerializedProperty property) (at ./Library/PackageCache/today.comes.saintsfield@0576082cbc43/Editor/Core/SaintsPropertyDrawerUIToolkit.cs:392)
SaintsField.Editor.Playa.Renderer.SerializedFieldRenderer.CreateSerializedUIToolkit () (at ./Library/PackageCache/today.comes.saintsfield@0576082cbc43/Editor/Playa/Renderer/SerializedFieldRendererUIToolkit.cs:147)
SaintsField.Editor.Playa.Renderer.BaseRenderer.SerializedFieldBaseRenderer.CreateTargetUIToolkit (UnityEngine.UIElements.VisualElement container) (at ./Library/PackageCache/today.comes.saintsfield@0576082cbc43/Editor/Playa/Renderer/BaseRenderer/SerializedFieldBaseRendererUIToolkit.cs:41)
SaintsField.Editor.Playa.Renderer.BaseRenderer.AbsRenderer.CreateVisualElement () (at ./Library/PackageCache/today.comes.saintsfield@0576082cbc43/Editor/Playa/Renderer/BaseRenderer/AbsRendererUIToolkit.cs:48)
SaintsField.Editor.SaintsEditor.CreateInspectorGUI () (at ./Library/PackageCache/today.comes.saintsfield@0576082cbc43/Editor/SaintsEditorUIToolkit.cs:59)
UnityEditor.UIElements.InspectorElement.CreateInspectorElementUsingUIToolkit (UnityEditor.Editor targetEditor) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement.CreateInspectorElementFromSerializedObject (UnityEditor.SerializedObject bindObject) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement.HandleEventBubbleUp (UnityEngine.UIElements.EventBase evt) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventBubbleUpInternal (UnityEngine.UIElements.EventBase evt) (at <7878115525854df7993c2f050b5b1154>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEvent_BubbleUpHandleEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement element, System.Boolean disabled) (at <7878115525854df7993c2f050b5b1154>:0)
UnityEngine.UIElements.EventDispatchUtilities.HandleEventAtTargetAndDefaultPhase (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.BaseVisualElementPanel panel, UnityEngine.UIElements.VisualElement target) (at <7878115525854df7993c2f050b5b1154>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.SendBindingEvent[TEventType] (TEventType evt, UnityEngine.UIElements.VisualElement target) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.BindTree (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedProperty parentProperty) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.ContinueBinding (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedProperty parentProperty) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.SerializedObjectBindingContext.Bind (UnityEngine.UIElements.VisualElement element) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.Bindings.DefaultSerializedObjectBindingImplementation.Bind (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedObject obj) (at <0f0b52ca76b24b5a86e5ec27d306db37>:0)
UnityEditor.UIElements.BindingExtensions.Bind (UnityEngine.UIElements.VisualElement element, UnityEditor.SerializedObject obj) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement..ctor (UnityEditor.SerializedObject obj, UnityEditor.Editor editor, UnityEditor.UIElements.InspectorElement+DefaultInspectorFramework defaultInspectorFramework) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement..ctor (UnityEditor.Editor editor, UnityEditor.UIElements.InspectorElement+DefaultInspectorFramework defaultInspectorFramework) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.InspectorElement..ctor (UnityEditor.Editor editor) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.EditorElement.BuildInspectorElement () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.UIElements.EditorElement.CreateInspectorElement () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.EditorElementUpdater.CreateInspectorElementsForMilliseconds (System.Int64 targetMilliseconds) (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.PropertyEditor.Update () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.HostView.SendUpdate () (at <95707308f6f3498991e9df8902fe97ba>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <95707308f6f3498991e9df8902fe97ba>:0)
```

okay, line number looks different

**Comment by TylerTemp** [comment]
`Obvious.Soap.Editor.ScriptableBasePropertyDrawer` does not have a default constructor thus the fallback get null... I'll see what I can do

**Comment by TylerTemp** [comment]
Fixed. Will release it soon today

![Image](https://github.com/user-attachments/assets/70486c94-2625-41ba-9403-c96e0507e2b3)

**Comment by TylerTemp** [comment]
Fixed in [4.1.1](https://github.com/TylerTemp/SaintsField/releases/tag/4.1.1)

**Comment by locus84** [comment]
![Image](https://github.com/user-attachments/assets/5ba3cfa3-ab7e-48f5-81e0-81eeb38c0851)

With 4.1.1 there's no error!
But the arrow in front of the field overlaps label
And inline editors are drawn multiple times(two, actually)

**Comment by TylerTemp** [comment]
Moved to #193
