### ISSUE TITLE
[Feature Request] Serialize some fields via ISerializationCallbackReceiver like how is it done in OdinSerializer

### ISSUE THREAD

**Issue by potokaalex** [TylerTemp/SaintsField#236]
Hi, there seems to be a problem with displaying the enum name in the SaintsDictionary.
```
public SaintsDictionary<CollectableType, Color> Colors;
```
```
    public enum CollectableType
    {
        None = 0,
        Missile = 1,
        Coin = 2,
        Shield = 3,
    }
```
![Image](https://github.com/user-attachments/assets/89ac3974-f770-42ea-a0e7-a59000cbc875)
Ui toolkit
Staints 4.13.0
Unity 2022.3.57f1

One more question: why not serialize the System.Collections.Generic.Dictionary via ISerializationCallbackReceiver how is it done in OdinSerializer?

**Comment by TylerTemp** [comment]
Thanks for this reporting!

This is fixed in dev branch. Will release it tomorrow :)

**Comment by potokaalex** [comment]
The issue of ISerializationCallbackReceiver is still relevant. I think this will get rid of your Data types, yes, it will require some kind of abstract class, similar to saintsMonoBehaviour and saintsScriptableObject, but it may even be a plus, in case of conflicts with other solutions, and will allow the user to choose.

**Comment by TylerTemp** [comment]
Hi,

`ISerializationCallbackReceiver` will not be considered for the following reasons:

1.  Unity itself still has some bugs in serialization. With years of Unity game developing, I sometime still face the issue that something is missing, broken, or Unity failed to refresh a target.
2.  Odin (Odin Serializer), based on my previous experience, has an issue with serialization `Dictionary<T, enumFlagType>`. I didn't find anyone mentioning it on the internet; it only happens in one simple script of mine, and I have never found a solution
3.  `SaintsField` is still heavily focused on portable types & attributes, which means most data types & attributes should work either fine or good enough (e.g., without SaintsEditor, all auto getters work just fine, but they will require you to click on that `+` button on a list/array)
4. An IDE like Rider can not detect a custom `MonoBehavior` serializable dictionary

A `ISerializationCallbackReceiver` adds way too much complexity, and it will be a pain to locate a bug, even to see if it's related to this function.

**Comment by TylerTemp** [comment]
Hi,

this is fixed in [4.13.1](https://github.com/TylerTemp/SaintsField/releases/tag/4.13.1), please have a try

![Image](https://github.com/user-attachments/assets/4c0da43e-e01c-4238-9811-8bd1fe967f4f)

**Comment by potokaalex** [comment]
Hi, thanks for the efficiency. I still don't like the idea of custom serializable standard types. Well, maybe I'll integrating odin serializer with saintsField in my project. If it succeeds, I will let you know.

**Comment by TylerTemp** [comment]
Im re-considering this feature because ISerializationCallbackReceiver should solve many problems, including #289

**Comment by TylerTemp** [comment]
Added in [5.5.3](https://github.com/TylerTemp/SaintsField/releases/tag/5.5.3)
