### ISSUE TITLE
[Bug] SerializeReference, ReferencePicker Selected Item not updated

### ISSUE THREAD

**Issue by oguzhanakpulat** [TylerTemp/SaintsField#352]
<img width="958" height="149" alt="Image" src="https://github.com/user-attachments/assets/1d3ab4f8-735a-46ea-a932-faddbbd68419" />

![Image](https://github.com/user-attachments/assets/d271671c-0bb3-4913-a97e-f0b3660cc4b3)

Also in arrays IFoo[] _test, when i try to switch class from picker it throws until i switch class again

<img width="895" height="167" alt="Image" src="https://github.com/user-attachments/assets/dad231b9-88ad-4980-87bd-be995396e10c" />

Unity version: 2022.3.62f2
SaintField version: 5.7.6 ShowInInspector Bug Fix

```csharp

    public class TestMb : SaintsMonoBehaviour
    {
        [SerializeReference, ReferencePicker] private ITestable _testable;

    }

    public interface ITestable
    {
        
    }

    [Serializable]
    public class Foo : ITestable
    {
        public float FooValue;
    }
    [Serializable]
    public class Bar : ITestable
    {
        public bool BarValue;
    }
    [Serializable]
    public class Baz : ITestable
    {
        public string BazValue;
    }

```

**Comment by TylerTemp** [comment]
Hi,

Im able to fix the issue, but I can not trigger the error you paste. Can you copy paste the error here so I can read the trackback?

**Comment by TylerTemp** [comment]
Fixed in [5.7.7](https://github.com/TylerTemp/SaintsField/releases/tag/5.7.7), please have a try.

Im unable to re-produce the error it shows. If you still see the error, please copy&paste the error so I can check the trackbac

**Comment by oguzhanakpulat** [comment]
![Image](https://github.com/user-attachments/assets/4a88ecba-9e21-487a-aa06-d8fa431fdd3b)

Its okay with classes that inherits only interface
But when its get complicated (interface + abstract) it throws randomly error.
Version: 5.7.7

```
public class TestMb : SaintsMonoBehaviour
{
    [SerializeReference, ReferencePicker] private ITestNode[] _nodes;
}

public interface ITestNode
{
}

[Serializable]
public abstract class CompositeNodeBase : ITestNode
{
    [SerializeReference, ReferencePicker] private ITestNode[] _childNodes;
    [SerializeField] private bool _isTest;
}

[Serializable]
public class FooCompositeNode : CompositeNodeBase
{
    [SerializeField] private float _fooValue;
}

[Serializable]
public class BarCompositeNode : CompositeNodeBase
{
    [SerializeField] private float _barValue;
}

[Serializable]
public class QuoxCompositeNode : CompositeNodeBase
{
    [SerializeField] private float _quoxValue;
}


[Serializable]
public class ANode : ITestNode
{
    [SerializeField] private float _a;
}


[Serializable]
public class BNode : ITestNode
{
    [SerializeField] private float _b;
}

[Serializable]
public class CNode : ITestNode
{
    [SerializeField] private float _c;
}

[Serializable]
public class DNode : ITestNode
{
    [SerializeField] private float _d;
}

[Serializable]
public class ENode : ITestNode
{
    [SerializeField] private float _e;
}
```

**Comment by TylerTemp** [comment]
Fixed in [5.7.8](https://github.com/TylerTemp/SaintsField/releases/tag/5.7.8), please have a try

**Comment by oguzhanakpulat** [comment]
using 5.7.8 error still exists

![Image](https://github.com/user-attachments/assets/d2d5037c-4e50-417c-b9d1-fde9fd138a87)

**Comment by TylerTemp** [comment]
https://github.com/user-attachments/assets/20e88f31-8847-4561-be97-354b6a624b3d

<img width="287" height="24" alt="Image" src="https://github.com/user-attachments/assets/5b96f587-dfdc-4210-b06b-f93b06f0a316" />

Hi,

Im unable to re-produce it under 2022.3.62f2 with script: https://github.com/TylerTemp/SaintsField/blob/f9f7fbb5d4f97ded4ba5e561a2bfdc4e82d6de69/Samples~/Scripts/IssueAndTesting/Issue/Issue352AbstractReferencePicker.cs

Can you click on the error message, ctrl+c, and then paste here (which will include the full traceback) so I can check?

**Comment by oguzhanakpulat** [comment]
```
ObjectDisposedException: SerializedProperty _nodes.Array.data[0]._childNodes has disappeared!
UnityEditor.SerializedProperty.get_arraySize () (at <4b8f645257c94d1296f440a10c6f388e>:0)
UnityEditor.UIElements.Bindings.ListViewSerializedObjectBinding.Update () (at <b54ef8ca9c3e48ce9da615ccc27b9784>:0)
UnityEngine.UIElements.VisualTreeBindingsUpdater.UpdateBindings () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.VisualTreeBindingsUpdater.Update () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.Panel.UpdateBindings () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.UpdateSchedulers () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.UIEventRegistration.UpdateSchedulers () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEditor.RetainedMode.UpdateSchedulers () (at <b54ef8ca9c3e48ce9da615ccc27b9784>:0)
```

```
InvalidOperationException: The operation is not possible when moved past all properties (Next returned false)
UnityEditor.SerializedProperty.get_arraySize () (at <4b8f645257c94d1296f440a10c6f388e>:0)
UnityEditor.UIElements.Bindings.ListViewSerializedObjectBinding.Update () (at <b54ef8ca9c3e48ce9da615ccc27b9784>:0)
UnityEngine.UIElements.VisualTreeBindingsUpdater.UpdateBindings () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.VisualTreeBindingsUpdater.Update () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.Panel.UpdateBindings () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.UpdateSchedulers () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEngine.UIElements.UIEventRegistration.UpdateSchedulers () (at <886395f7f3c74189a56ab6a83f489872>:0)
UnityEditor.RetainedMode.UpdateSchedulers () (at <b54ef8ca9c3e48ce9da615ccc27b9784>:0)
```

**Comment by TylerTemp** [comment]
Hi,

thanks for the feedback.

However, I'm unable to re-produce this issue (updated the video in my previous comment), and the traceback is from UI Toolkit's internal schedulers (which again, is untraceable...)

I'm not sure if it's related to [this](https://discussions.unity.com/t/array-data-1-has-dissappeared-when-setting-the-list-equal-to-another-list-with-length-1/925350), but UI Toolkit's property tracker is always a pain in the ass...

I'll see if I can find anything useful about this issue. 

ATM I made some changes to [`dev` branch](https://github.com/TylerTemp/SaintsField/tree/dev), you can have a try, but not guaranteed.

**Comment by TylerTemp** [comment]
Hi,

The error you paste should not impact the functionality; it should only appear because the UI Toolkit failed to track that property internally.

At the moment, as I can not re-produce it, I'll close it as `cant-reproduce`. Maybe someday I'll spot this issue and actually fix it.
